#!/usr/bin/env python3
"""Prepare and validate the ignored Android Release EMAS configuration."""

from __future__ import annotations

import argparse
import os
import stat
import sys
import tempfile
from pathlib import Path


APP_KEY_ENV = "AWIKI_ANDROID_EMAS_APP_KEY"
APP_SECRET_ENV = "AWIKI_ANDROID_EMAS_APP_SECRET"


class ConfigError(ValueError):
    pass


def _credential(name: str, value: str | None) -> str:
    if value is None or not value:
        raise ConfigError(f"{name} is required")
    if value != value.strip():
        raise ConfigError(f"{name} must not contain surrounding whitespace")
    if not value.isascii() or any(character.isspace() for character in value):
        raise ConfigError(f"{name} must be one non-empty ASCII token")
    if "\\" in value or "\x00" in value:
        raise ConfigError(f"{name} contains unsupported characters")
    if value.startswith("REPLACE_WITH_"):
        raise ConfigError(f"{name} still contains a placeholder")
    return value


def _parse_properties(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise ConfigError(f"EMAS configuration is missing: {path}")
    properties: dict[str, str] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(),
        start=1,
    ):
        line = raw_line.strip()
        if not line or line.startswith(("#", "!")):
            continue
        if "=" not in raw_line:
            raise ConfigError(f"invalid properties line {line_number}")
        key, value = raw_line.split("=", 1)
        key = key.strip()
        if not key:
            raise ConfigError(f"empty properties key on line {line_number}")
        if key in properties:
            raise ConfigError(f"duplicate properties key: {key}")
        properties[key] = value.strip()
    return properties


def validate_release_config(path: Path) -> None:
    properties = _parse_properties(path)
    if properties.get("release.enabled", "").casefold() != "true":
        raise ConfigError("release.enabled must be true")
    _credential("release.appKey", properties.get("release.appKey"))
    _credential("release.appSecret", properties.get("release.appSecret"))

    mode = stat.S_IMODE(path.stat().st_mode)
    if mode & 0o077:
        raise ConfigError("EMAS configuration permissions must not allow group or other access")


def write_release_config(path: Path) -> None:
    app_key = _credential(APP_KEY_ENV, os.environ.get(APP_KEY_ENV))
    app_secret = _credential(APP_SECRET_ENV, os.environ.get(APP_SECRET_ENV))
    if path.is_symlink():
        raise ConfigError(f"refusing to replace symlink: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        (
            "# Generated by the AWiki Me release workflow. Do not commit.",
            "debug.enabled=false",
            "profile.enabled=false",
            "release.enabled=true",
            f"release.appKey={app_key}",
            f"release.appSecret={app_secret}",
            "",
        )
    )
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            os.chmod(temporary_path, 0o600)
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_path, path)
        temporary_path = None
        os.chmod(path, 0o600)
        validate_release_config(path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)
    write = subcommands.add_parser("write", help="write a minimal Release config")
    write.add_argument("--output", type=Path, required=True)
    validate = subcommands.add_parser("validate", help="validate a Release config")
    validate.add_argument("--path", type=Path, required=True)
    return parser


def main() -> int:
    arguments = _parser().parse_args()
    try:
        if arguments.command == "write":
            write_release_config(arguments.output)
        else:
            validate_release_config(arguments.path)
    except (ConfigError, OSError, UnicodeError) as error:
        print(f"[android-emas-config] error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
